module.exports = {
  root: true,
  env: {
    node: true,
    es2022: true,
  },
  extends: [
    "airbnb-base",
    "airbnb-typescript/base",
    "plugin:@typescript-eslint/recommended-type-checked",
    "plugin:@typescript-eslint/stylistic-type-checked",
    "prettier",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
    project: ["./packages/*/tsconfig.json", "./apps/*/tsconfig.json"],
    tsconfigRootDir: __dirname,
  },
  plugins: ["@typescript-eslint", "prettier"],
  rules: {
    "prettier/prettier": "warn",
    "@typescript-eslint/no-unsafe-assignment": "warn",
    "@typescript-eslint/no-unsafe-call": "warn",
    "@typescript-eslint/no-unsafe-member-access": "warn",
    "@typescript-eslint/no-unsafe-argument": "warn",
    "@typescript-eslint/no-unsafe-return": "warn",
    "no-plusplus": "off",
    "no-continue": "warn",
    "no-underscore-dangle": "off",
    "import/no-duplicates": "warn",
    "import/order": "warn",
    "import/first": "warn",
    "@typescript-eslint/no-shadow": "warn",
    "@typescript-eslint/unbound-method": "off",
    "@typescript-eslint/no-unused-vars": [
      "warn",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      },
    ],
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/no-floating-promises": "warn",
    "@typescript-eslint/no-misused-promises": [
      "warn",
      {
        "checksConditionals": false,
        "checksVoidReturn": false,
      },
    ],
    "import/no-extraneous-dependencies": "off",
    "import/prefer-default-export": "off",
    "arrow-body-style": "off",
    "no-console": "off",
    "no-restricted-syntax": "off",
    "no-await-in-loop": "off",
    "class-methods-use-this": "off",
    "consistent-return": "off",
    "@typescript-eslint/require-await": "warn",
    "@typescript-eslint/restrict-template-expressions": "warn",
    "@typescript-eslint/prefer-nullish-coalescing": "warn",
    "@typescript-eslint/no-unsafe-enum-comparison": "warn",
    "@typescript-eslint/no-var-requires": "warn",
    "@typescript-eslint/no-use-before-define": "warn",
    "@typescript-eslint/no-unnecessary-type-assertion": "warn",
    "@typescript-eslint/lines-between-class-members": "off",
    "@typescript-eslint/array-type": "off",
    "global-require": "off",
    "no-restricted-globals": "off",
    "prefer-template": "off",
    "max-classes-per-file": "off",
    "no-param-reassign": [
      "error",
      {
        "props": false,
      },
    ],
  },
  ignorePatterns: ["dist/", "node_modules/", "*.config.js"],
};