version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: newsflow-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - ./apps/backend/src:/app/apps/backend/src
      - ./packages/shared/src:/app/packages/shared/src
      - ./packages/database/src:/app/packages/database/src
      - ./packages/database/prisma:/app/packages/database/prisma
    command: sh -c "pnpm --filter=database db:push && pnpm dev"
